name: upload-prod-store

env:
  NODE_OPTIONS: '--max_old_space_size=6144'
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

on:
  push:
    branches:
      - release

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_HUB_TOKEN }}

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Upload to Production Store
        uses: blocklet/action-workflow@v1
        env:
          COMPONENT_STORE_URL: ${{ secrets.STORE_ENDPOINT_PROD }}
        with:
          skip-deps: true
          skip-upload: false
          skip-deploy: true
          skip-release: true
          bundle-command: pnpm bundle
          working-directory: blocklets/snap-kit
          store-endpoint: ${{ secrets.STORE_ENDPOINT_PROD }}
          store-access-token: ${{ secrets.STORE_ACCESS_TOKEN_PROD }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
          github-token: ${{ secrets.GIT_HUB_TOKEN }}
