name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened]
    branches:
      - master

concurrency:
  group: ${{ github.repository }}-${{ github.event.number || github.head_ref ||
    github.sha }}-${{ github.workflow }}-${{ github.event_name ==
    'pull_request_review_comment' && 'pr_comment' || 'pr' }}
  cancel-in-progress: ${{ github.event_name != 'pull_request_review_comment' }}

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: blocklet/aigne-code-reviewer@v0.1.14
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          DEBUG: '@aigne/*'
        with:
          debug: true
          language: 'zh-CN'
          review_simple_changes: false
          review_comment_lgtm: false
          path_filters: |
            !**/*.md
            !**/package.json
            !**/pnpm-lock.yaml
            !**/blocklet.yml
            !**/blocklet.prefs.json
            !**/types.js
            !**/*.d.ts
            !**/*.lock
